import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as SonnerToaster } from "sonner";
import Loader from "@/components/ui/loader";
import "mapbox-gl/dist/mapbox-gl.css";
import { Header } from "@/components/Header";
import { verifyUser } from "@/lib/roles";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Dashboard - HaciendaX",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const verifyStatus = await verifyUser();

  if (!verifyStatus) {
    redirect("/onboarding");
  }
  return (
    <div className="overflow-hidden bg-white">
      {/* <Navbar /> */}
      <Header isDashboard />
      {/* <section
        id="dashboard"
        className=""
      > */}
      <Suspense fallback={<Loader />}>{children}</Suspense>
      {/* </section> */}
      <Toaster />
      <SonnerToaster expand richColors />
    </div>
  );
}
