import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";
import "mapbox-gl/dist/mapbox-gl.css";
import Navbar from "./_components/Navbar";
import { Toaster as SonnerToaster } from "sonner";
import Loader from "@/components/ui/loader";
import { currentUser } from "@clerk/nextjs/server";
import { SignIn } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Dashboard - HaciendaX",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await currentUser();

  if (!auth) return SignIn;

  return (
    <div className="overflow-hidden bg-white">
      <Navbar />
      {/* <section
        id="dashboard"
        className=""
      > */}
      <Suspense fallback={<Loader />}>{children}</Suspense>
      {/* </section> */}
      <Toaster />
      <SonnerToaster expand richColors />
    </div>
  );
}
