import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";
import "mapbox-gl/dist/mapbox-gl.css";
import Navbar from "./_components/Navbar";
import { Toaster as SonnerToaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Dashboard - HaciendaX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <div className="w-full justify-center flex items-center flex-col  bg-[#ffff]">
        <Navbar />
        <section id="dashboard" className="w-full h-full flex justify-center items-center lg:max-w-6xl bg-[#ffff]">
          {children}
        </section>
        <Toaster />
        <SonnerToaster expand richColors />
        {/* <Footer /> */}
      </div>
    </Suspense>
  );
}
