import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "./_components/Navbar";
import { Toaster as SonnerToaster } from "sonner";
import Loader from "@/components/ui/loader";
import "mapbox-gl/dist/mapbox-gl.css";
import { UserContextProvider } from "@/lib/userContext";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Dashboard - HaciendaX",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="overflow-hidden bg-white">
      <Navbar />
      {/* <section
        id="dashboard"
        className=""
      > */}
      <Suspense fallback={<Loader />}>
        <UserContextProvider>{children}</UserContextProvider>
      </Suspense>
      {/* </section> */}
      <Toaster />
      <SonnerToaster expand richColors />
    </div>
  );
}
