import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { PHProvider } from "@/components/Providers/PostHogProvider";
import dynamic from "next/dynamic";
import "mapbox-gl/dist/mapbox-gl.css";
import Providers from "@/components/Providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <PHProvider> */}
      <Providers>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            inter
          )}
        >
          {/* <ClerkProvider appearance={{}}> */}
          {/* <PostHogPageView /> */}
          <Suspense fallback={<div>Loading...</div>}>
            <div style={{ background: "var(--black)", overflow: "hidden" }}>
              <Header />
              {children}
              <Toaster />
            </div>
            <Footer />
          </Suspense>
          {/* </ClerkProvider> */}
        </body>
      </Providers>
      {/* </PHProvider> */}
    </html>
  );
}
