import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import ReactQueryProvider from "@/Utils/ReactQueryProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { PHProvider } from "@/components/PostHogProvider";
import dynamic from "next/dynamic";
import "mapbox-gl/dist/mapbox-gl.css";

const inter = Inter({ subsets: ["latin"] });

const PostHogPageView = dynamic(() => import("./PostHogPageView"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PHProvider>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            inter
          )}
        >
          <ReactQueryProvider>
            <ClerkProvider appearance={{}}>
              <PostHogPageView />
              <Suspense fallback={<div>Loading...</div>}>
                <div style={{ background: "var(--black)", overflow: "hidden" }}>
                  <Header />
                  {children}
                  <Toaster />
                </div>
                <Footer />
              </Suspense>
            </ClerkProvider>
          </ReactQueryProvider>
        </body>
      </PHProvider>
    </html>
  );
}
