import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={inter.className}
        style={{ margin: 0, padding: 0, overflowX: "hidden" }}
      >
        <div className="min-h-screen bg-background font-sans antialiased tracking-wider">
          <main className="App pt-2 bg-black" style={{ minHeight: "100vh" }}>
            {children}
          </main>
=======
      <body className={inter.className}>
        <div className="min-h-screen bg-background font-sans antialiased tracking-wider w-full">
          <div className="pt-5 pr-20 pl-20 bg-background w-full">
            <Navbar />
            <main className="w-full">{children}</main>
            <Footer />
          </div>
>>>>>>> d23ab02ea820264bf0e33569a91cec91dcf189f1
        </div>
      </body>
    </html>
  );
}
