import type { Metadata } from "next";
import "mapbox-gl/dist/mapbox-gl.css";
import Footer from "@/components/Footer";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PropertyLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div style={{ background: "bg-white", overflow: "hidden" }}>
        <Header />
        {children}
      </div>
      <Footer />
    </>
  );
}
