import { Suspense } from "react";
import type { Metadata } from "next";
import "mapbox-gl/dist/mapbox-gl.css";
import Footer from "@/components/Footer";
import { Header } from "@/components/Header";
import Loader from "@/components/ui/loader";

export const metadata: Metadata = {
  title: "Hacienda X - Core",
  description: "Generated by create next app",
};

export default function CoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div style={{ background: "bg-white", overflow: "hidden" }}>
      <Suspense fallback={<Loader />}>
        <Header />
        {children}
        <Footer />
      </Suspense>
    </div>
  );
}
